name: GEDHTML actions
run-name: ${{ github.actor }} is running pytest on GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  run-tests-and-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only dev
      - name: run tests
        run: |
          poetry run pytest
      - name: run linters
        run: |
          poetry run ruff check .
          poetry run mypy .
