name: linting and testing
run-name: ${{ github.actor }} is running linting and testing on GitHub Actions
on: [push]
permissions:
  contents: write
jobs:
  run-tests-and-linters:
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v3
      - name: set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: run tests
        run: |
          poetry run pytest
      - name: run linter
        run: |
          poetry run ruff check .
      - name: run type check
        run: |
          poetry run mypy .
