name: publish
run-name: ${{ github.actor }} is publishing a new version with GitHub Actions 🚀
on:
  push:
    tags:
      - v**

permissions:
  contents: write
jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v3
      - name: set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - run: |
          poetry version ${{ github.ref_name }}
          poetry build
          poetry publish --dry-run
