name: publish
run-name: ${{ github.actor }} is publishing a new version with GitHub Actions 🚀
on:
  push:
    tags:
      - v**
      # Or we could use the stricter 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
jobs:
  publish-code:
    runs-on: ubuntu-latest
    steps:
      - run: |
          poetry version ${{ github.ref_name }}
          poetry build
          poetry publish --dry-run
