name: publish
run-name: ${{ github.actor }} is publishing a new version with GitHub Actions 🚀
on:
  workflow_run:
    workflows: [linting and testing]
    types: 
      - completed
    branches:  # Also works for tags
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
jobs:
  publish-code:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: get latest code
        uses: actions/checkout@v3
      - name: set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: build new version
        run: |
          poetry version ${{ github.ref_name }}
          poetry build
      - name: publish
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
  publish-fail:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Throw error
        run: |
          echo Could not publish because testing/linting job failed.
          exit 1
